version: "3.9"

services:
  comejaca_database:
    image: postgres
    container_name: comejaca_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=comejaca
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=passw
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: comejaca_api
    restart: always
    ports:
      - 3003:3003
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - comejaca_database
    depends_on:
      - comejaca_database
volumes:
  pgdata:
    driver: local
